use secrets for certificates
Icinga/helm-charts pull request #24
Opened 2023-08-04 16:03 UTC by CanisLupusLupus

This PR resolves issue #21.

Certificates are projected in containers using kubernets secrets and are mounted in `/etc/icinga2-pki/<feature>/` directory. On enabling TLS/SSL in feature all certificates are required (i.e. ca, cert and key).

Sample configuration for elasticsearch:
```
icinga2:
  features:
    elasticsearch:
      enabled: true
      secretName: icinga-elasticsearch-secret
      enable_tls: true
      caSecretKey: ca
      certSecretKey: cert
      keySecretKey: key
```

Besides resolving issue #21 there are some more related changes:
- I've renamed `.Values.global.redis.password` to `.Values.features.icingadb.password.value` and enabled configuration via value/secret (I've overloked this sensible value in PR #17)
- default value for `.Values.features.influxdb.service_template` is updated (closing `}`) was missing

2023-08-07 08:46 UTC, mocdaniel requested changes
Thank you for your contribution. I hate to be a buzzkill here, but after some consideration, I don't particularly like the idea of configuring all secret information related to a service inside of a single secret. Mainly because that makes it harder to integrate external secrets via operators because, in external sources, those groupings might not exist.

I suggest changing our approach to using dedicated secrets `tlsSecret` and `credSecret` for a separation of concerns.

Could you refactor your PR to reflect those changes? If that's too much of a chore I can take over from here and co-author this PR.

2023-08-07 20:59 UTC, CanisLupusLupus commented
I agree, it's better design to have separate secrets (and it also makes charts more flexible and easier to use...).

I'll go ahead and refactor the PR in coming days.

2023-08-11 21:39 UTC, CanisLupusLupus commented
I've refactored the PR to use dedicated `credSecret`/`tlsSecret` instead of `secretName`.

2023-08-11 21:56 UTC, mocdaniel approved these changes

2023-08-11 21:56 UTC, mocdaniel commented
LGTM!

2023-08-11 21:56 UTC, merged